### ISSUE TITLE
友情链接 | 谬蜀黍

### ISSUE THREAD

**Issue by Miuss** [Miuss/miuss-gitment#15]
https://miuss.org/links/

**Comment by tetsaicn** [comment]
05不如交有一个朋友？
https://www.tetsai.com
另外，网站感觉很卡啊，加一点优化，上一点预加载和预读取

**Comment by Miuss** [comment]
@tetsaicn 我的网站用的CodingPages所以会卡一些，您的博客站点打不开呀。

**Comment by tetsaicn** [comment]
那个啥，网站已经倒闭233
